// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whhwgwggtmlqlxjottru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoaHdnd2dndG1scWx4am90dHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDM5ODgsImV4cCI6MjA3MzUxOTk4OH0.Rznt2IE9yFCrve30OOxA13AqR5seltvfLfcZP3EXTOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});