// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfldvqcmqfcyzuurdfse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmbGR2cWNtcWZjeXp1dXJkZnNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODYzNzMsImV4cCI6MjA3NDI2MjM3M30.Wbf3cKD-sMCQnPnGhGFv6r5_Ib9lP90hPPh52LpwfPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});